### PR TITLE
Support "Start Recruitment/Close Recruitment" teams

### PR DESCRIPTION
**Pull request by lamsion**
1. add team status
2. fix team search list

### CODE REVIEW

**Comment by lamsion** [comment]
@WiktorStarczewski , please help me to review this PR, thanks!

**Comment by ClarenceL** [comment]
We will merge staging into master by Monday, perhaps u can rebase this on master later

**Comment by lamsion** [comment]
@ClarenceL may I rebase on latest staging branch rather than master?

**Comment by lamsion** [comment]
@WiktorStarczewski @ClarenceL I change the code to align the latest requirement, and also rebased on latest staging branch.

**Pull request closed without merging**
